apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-openidm
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/local/postgres-openidm/
