apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-openidm
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/local/postgres-openidm/
